from sqlalchemy import Column, Integer, String, Float, ForeignKey, DateTime, Boolean, JSON
from sqlalchemy.orm import relationship
from datetime import datetime
from app.core.database import Base

class MonitoringDevice(Base):
    """
    Extensions for IoTDevices specifically for Livestock Shelters.
    Can be a Camera, SensorHub, or ActuatorController.
    """
    __tablename__ = "livestock_monitoring_devices"

    id = Column(Integer, primary_key=True, index=True)
    housing_id = Column(Integer, ForeignKey("livestock_housing.id"), nullable=False)
    name = Column(String) 
    device_type = Column(String) # "CAMERA", "SENSOR_HUB", "FEEDER_CONTROLLER", "LIGHT_CONTROLLER"
    
    # Network / Connection details
    stream_url = Column(String, nullable=True) # For Cameras (RTSP/HLS)
    api_endpoint = Column(String, nullable=True) # For direct polling
    is_active = Column(Boolean, default=True)
    
    # Configuration
    settings = Column(JSON, default={}) # {"motion_sensitivity": 0.8, "alert_zones": []}
    
    housing = relationship("app.modules.livestock.models.LivestockHousing", backref="smart_devices")
    alerts = relationship("MonitoringAlert", back_populates="device")


class MonitoringAlert(Base):
    """
    Alerts generated by Cameras (motion) or Sensors (audio/temp).
    """
    __tablename__ = "livestock_monitoring_alerts"

    id = Column(Integer, primary_key=True, index=True)
    device_id = Column(Integer, ForeignKey("livestock_monitoring_devices.id"))
    timestamp = Column(DateTime, default=datetime.utcnow)
    
    alert_type = Column(String) # "MOTION", "SOUND", "TEMP_HIGH", "AMMONIA_HIGH", "INTRUSION"
    severity = Column(String) # "INFO", "WARNING", "CRITICAL"
    message = Column(String)
    
    # Evidence
    snapshot_url = Column(String, nullable=True) # Image of the event
    clip_url = Column(String, nullable=True) # Video clip
    data_value = Column(Float, nullable=True) # e.g., 45.5 (degrees)
    
    resolved = Column(Boolean, default=False)
    resolved_at = Column(DateTime, nullable=True)
    
    device = relationship("MonitoringDevice", back_populates="alerts")


class TelemetryReading(Base):
    """
    Time-series data for environmental sensors.
    """
    __tablename__ = "livestock_telemetry"

    id = Column(Integer, primary_key=True, index=True)
    device_id = Column(Integer, ForeignKey("livestock_monitoring_devices.id"))
    timestamp = Column(DateTime, default=datetime.utcnow)
    
    temperature = Column(Float, nullable=True)
    humidity = Column(Float, nullable=True)
    co2_level = Column(Float, nullable=True)
    ammonia_level = Column(Float, nullable=True)
    noise_level_db = Column(Float, nullable=True) # Audio monitoring
    
    luminosity = Column(Float, nullable=True) # Light level


class SmartDeviceLog(Base):
    """
    Log of user interactions with smart devices to generate usage patterns/suggestions.
    """
    __tablename__ = "livestock_smart_device_logs"

    id = Column(Integer, primary_key=True, index=True)
    device_id = Column(Integer, ForeignKey("livestock_monitoring_devices.id"))
    timestamp = Column(DateTime, default=datetime.utcnow)
    action = Column(String) # "TURN_ON", "TURN_OFF", "SET_VALUE"
    details = Column(String, nullable=True) # e.g. "Scheduled via suggestion"
